## Importing Pandas

In [40]:
import pandas as pd

### opening a local csv file

In [41]:
df = pd.read_csv("dataset.csv")

In [42]:
df

,user_id,session_id,timestamp,profession,tool,use_case,iterations,prompt_complexity,quality_with_ai,quality_without_ai,...,overreliance_score,learning_loss,hallucination_flag,failure_type,ease_of_use,ui_complexity,requires_login,subscription_type,session_length,deadline_pressure
0,43140,3817,2024-10-27 03:19:50,Software Developer,ChatGPT,Blog Writing,5,low,10.0,4.139299,...,8.38,1,0,none,9,low,1,freemium,13,low
1,9263,89304,2023-11-19 05:49:56,Architect,Perplexity AI,Medical Notes,4,medium,8.0,6.379619,...,7.27,0,0,none,5,medium,1,paid,6,medium
2,33655,113595,2023-08-29 17:39:22,HR Manager,Grammarly AI,Image Generation,6,low,9.0,6.240725,...,5.14,0,0,none,7,medium,0,paid,56,medium
3,11705,155151,2023-03-18 08:10:46,Accountant,Claude,Marketing Copy,3,medium,7.5,6.113465,...,7.73,0,0,none,10,low,1,free,44,high
4,4384,4358,2023-12-04 14:00:47,Scientist,Gemini,Marketing Copy,2,medium,7.0,5.221701,...,3.65,0,0,none,7,medium,0,freemium,36,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,17144,22133,2023-04-08 13:24:06,Student,Cursor AI,Resume Building,4,high,8.0,6.322623,...,8.03,0,1,incomplete,8,medium,0,free,39,high
4996,49443,64573,2023-05-27 00:23:04,Professor,Cursor AI,Research Summary,2,high,7.0,3.860208,...,7.85,1,0,none,6,low,0,free,9,low
4997,3097,198064,2023-02-10 17:37:03,Mechanical Engineer,Midjourney,Marketing Copy,1,high,6.5,4.667756,...,8.50,0,0,none,9,low,0,free,17,high
4998,42128,170752,2023-03-21 16:00:17,HR Manager,DALL-E,Resume Building,3,medium,7.5,5.447681,...,6.68,0,0,none,5,medium,1,free,34,low
4999,4210,181799,2023-02-18 12:42:52,YouTuber,AutoGPT,Code Generation,1,medium,6.5,5.948105,...,8.87,0,0,none,6,medium,1,freemium,16,low

### Opening a csv file from url

import requests
from io import StringIO

url = ""
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

In [43]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [44]:
import requests
import pandas as pd
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

df_countries = pd.read_csv(data)

# Save to CSV locally
df_countries.to_csv("countries.csv", index=False)

## Sep Parameter

In [45]:
pd.read_csv('movie_titles_metadata.tsv')

    m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0    m1\t1492: conquest of paradise\t1992\t6.20\t10...
1    m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2    m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3    m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4    m5\tthe fifth element\t1997\t7.50\t133756\t['a...
..                                                 ...
611  m612\twatchmen\t2009\t7.80\t135229\t['action' ...
612  m613\txxx\t2002\t5.60\t53505\t['action' 'adven...
613  m614\tx-men\t2000\t7.40\t122149\t['action' 'sc...
614  m615\tyoung frankenstein\t1974\t8.00\t57618\t[...
615  m616\tzulu dawn\t1979\t6.40\t1911\t['action' '...

[616 rows x 1 columns]

In [46]:
# sep='parameter' , seperates the baced on the delimitor , in csv , comma is default , 

pd.read_csv('movie_titles_metadata.tsv' , sep='\t')

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [47]:
# names = [ list column names] , used to add column names

pd.read_csv('movie_titles_metadata.tsv' , sep='\t' , names=["sno" , 'Title','Year' , 'Rating' , "Votes" ,'Geners' ])

,sno,Title,Year,Rating,Votes,Geners
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

## Index_col parameter

In [48]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [49]:
pd.read_csv('aug_train.csv' , index_col='enrollee_id')

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## Header Parameter

In [50]:
pd.read_csv("dataset.csv")

,user_id,session_id,timestamp,profession,tool,use_case,iterations,prompt_complexity,quality_with_ai,quality_without_ai,...,overreliance_score,learning_loss,hallucination_flag,failure_type,ease_of_use,ui_complexity,requires_login,subscription_type,session_length,deadline_pressure
0,43140,3817,2024-10-27 03:19:50,Software Developer,ChatGPT,Blog Writing,5,low,10.0,4.139299,...,8.38,1,0,none,9,low,1,freemium,13,low
1,9263,89304,2023-11-19 05:49:56,Architect,Perplexity AI,Medical Notes,4,medium,8.0,6.379619,...,7.27,0,0,none,5,medium,1,paid,6,medium
2,33655,113595,2023-08-29 17:39:22,HR Manager,Grammarly AI,Image Generation,6,low,9.0,6.240725,...,5.14,0,0,none,7,medium,0,paid,56,medium
3,11705,155151,2023-03-18 08:10:46,Accountant,Claude,Marketing Copy,3,medium,7.5,6.113465,...,7.73,0,0,none,10,low,1,free,44,high
4,4384,4358,2023-12-04 14:00:47,Scientist,Gemini,Marketing Copy,2,medium,7.0,5.221701,...,3.65,0,0,none,7,medium,0,freemium,36,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,17144,22133,2023-04-08 13:24:06,Student,Cursor AI,Resume Building,4,high,8.0,6.322623,...,8.03,0,1,incomplete,8,medium,0,free,39,high
4996,49443,64573,2023-05-27 00:23:04,Professor,Cursor AI,Research Summary,2,high,7.0,3.860208,...,7.85,1,0,none,6,low,0,free,9,low
4997,3097,198064,2023-02-10 17:37:03,Mechanical Engineer,Midjourney,Marketing Copy,1,high,6.5,4.667756,...,8.50,0,0,none,9,low,0,free,17,high
4998,42128,170752,2023-03-21 16:00:17,HR Manager,DALL-E,Resume Building,3,medium,7.5,5.447681,...,6.68,0,0,none,5,medium,1,free,34,low
4999,4210,181799,2023-02-18 12:42:52,YouTuber,AutoGPT,Code Generation,1,medium,6.5,5.948105,...,8.87,0,0,none,6,medium,1,freemium,16,low

In [51]:
## header makes a specified row as column names 

pd.read_csv("dataset.csv" , header=1)

,43140,3817,2024-10-27 03:19:50,Software Developer,ChatGPT,Blog Writing,5,low,10.0,4.139298798163761,...,8.38,1,0,none,9,low.1,1.1,freemium,13,low.2
0,9263,89304,2023-11-19 05:49:56,Architect,Perplexity AI,Medical Notes,4,medium,8.0,6.379619,...,7.27,0,0,none,5,medium,1,paid,6,medium
1,33655,113595,2023-08-29 17:39:22,HR Manager,Grammarly AI,Image Generation,6,low,9.0,6.240725,...,5.14,0,0,none,7,medium,0,paid,56,medium
2,11705,155151,2023-03-18 08:10:46,Accountant,Claude,Marketing Copy,3,medium,7.5,6.113465,...,7.73,0,0,none,10,low,1,free,44,high
3,4384,4358,2023-12-04 14:00:47,Scientist,Gemini,Marketing Copy,2,medium,7.0,5.221701,...,3.65,0,0,none,7,medium,0,freemium,36,medium
4,28467,113897,2024-07-02 10:26:29,Business Analyst,Canva AI,Code Generation,4,medium,8.0,5.816263,...,6.31,0,0,none,10,medium,1,paid,34,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,17144,22133,2023-04-08 13:24:06,Student,Cursor AI,Resume Building,4,high,8.0,6.322623,...,8.03,0,1,incomplete,8,medium,0,free,39,high
4995,49443,64573,2023-05-27 00:23:04,Professor,Cursor AI,Research Summary,2,high,7.0,3.860208,...,7.85,1,0,none,6,low,0,free,9,low
4996,3097,198064,2023-02-10 17:37:03,Mechanical Engineer,Midjourney,Marketing Copy,1,high,6.5,4.667756,...,8.50,0,0,none,9,low,0,free,17,high
4997,42128,170752,2023-03-21 16:00:17,HR Manager,DALL-E,Resume Building,3,medium,7.5,5.447681,...,6.68,0,0,none,5,medium,1,free,34,low
4998,4210,181799,2023-02-18 12:42:52,YouTuber,AutoGPT,Code Generation,1,medium,6.5,5.948105,...,8.87,0,0,none,6,medium,1,freemium,16,low

## Use_columns Parameter

In [52]:
pd.read_csv("aug_train.csv")

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [53]:
## in usecolumns we can specify the columns that we only wanted

pd.read_csv('aug_train.csv' , usecols=['enrollee_id' , 'gender' , 'relevent_experience'])

       enrollee_id gender      relevent_experience
0             8949   Male  Has relevent experience
1            29725   Male   No relevent experience
2            11561    NaN   No relevent experience
3            33241    NaN   No relevent experience
4              666   Male  Has relevent experience
...            ...    ...                      ...
19153         7386   Male   No relevent experience
19154        31398   Male  Has relevent experience
19155        24576   Male  Has relevent experience
19156         5756   Male  Has relevent experience
19157        23834    NaN   No relevent experience

[19158 rows x 3 columns]

## squeeze parameter

In [54]:
df = pd.read_csv('aug_train.csv', usecols=['gender'])
gender_series = df['gender']

df

      gender
0       Male
1       Male
2        NaN
3        NaN
4       Male
...      ...
19153   Male
19154   Male
19155   Male
19156   Male
19157    NaN

[19158 rows x 1 columns]

In [55]:
gender_series

0        Male
1        Male
2         NaN
3         NaN
4        Male
         ...
19153    Male
19154    Male
19155    Male
19156    Male
19157     NaN
Name: gender, Length: 19158, dtype: object

## Skiprows / nrows parameters

In [56]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [57]:
pd.read_csv("aug_train.csv" , skiprows=[1,2,3,4,5]) # skiprows skips specified rows and desplays remaining all rows

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
1,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
2,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
3,27107,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,50-99,Pvt Ltd,1,46,1.0
4,699,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,17,10000+,Pvt Ltd,>4,123,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19148,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19149,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19150,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19151,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19152,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [58]:
pd.read_csv('aug_train.csv' , nrows=100) #nrows takes only limited n no of rows of data

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

## loading a huge dataset into chunks

In [82]:
dfs = pd.read_csv("aug_train.csv" , chunksize=5000)

In [83]:
dfs

In [79]:
for chunks in dfs:
    print(chunks.shape)
    print(chunks.size)

(5000, 14)
70000
(5000, 14)
70000
(5000, 14)
70000
(4158, 14)
58212

In [84]:
for i in dfs:
    print(i)

      enrollee_id      city  city_development_index  gender  \
0            8949  city_103                   0.920    Male
1           29725   city_40                   0.776    Male
2           11561   city_21                   0.624     NaN
3           33241  city_115                   0.789     NaN
4             666  city_162                   0.767    Male
...           ...       ...                     ...     ...
4995         7892   city_21                   0.624  Female
4996        19768   city_21                   0.624    Male
4997        33180   city_16                   0.910    Male
4998        13215  city_103                   0.920  Female
4999         2386   city_21                   0.624    Male

          relevent_experience enrolled_university education_level  \
0     Has relevent experience       no_enrollment        Graduate
1      No relevent experience       no_enrollment        Graduate
2      No relevent experience    Full time course        Graduate
3      No relevent experience                 NaN        Graduate
4     Has relevent experience       no_enrollment         Masters
...                       ...                 ...             ...
4995  Has relevent experience       no_enrollment        Graduate
4996   No relevent experience       no_enrollment        Graduate
4997   No relevent experience       no_enrollment     High School
4998  Has relevent experience       no_enrollment        Graduate
4999  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size    company_type last_new_job  \
0                STEM        >20          NaN             NaN            1
1                STEM         15        50-99         Pvt Ltd           >4
2                STEM          5          NaN             NaN        never
3     Business Degree         <1          NaN         Pvt Ltd        never
4                STEM        >20        50-99  Funded Startup            4
...               ...        ...          ...             ...          ...
4995             STEM          3      100-500             NaN            1
4996             STEM          3      100-500         Pvt Ltd            1
4997              NaN        >20    5000-9999         Pvt Ltd           >4
4998             STEM         10       10000+         Pvt Ltd           >4
4999             STEM          2    5000-9999         Pvt Ltd            2

      training_hours  target
0                 36     1.0
1                 47     0.0
2                 83     0.0
3                 52     1.0
4                  8     0.0
...              ...     ...
4995             114     1.0
4996              64     1.0
4997              89     0.0
4998              20     1.0
4999              16     0.0

[5000 rows x 14 columns]
      enrollee_id      city  city_development_index  gender  \
5000        18582   city_83                   0.923    Male
5001        25222  city_159                   0.843     NaN
5002         5697   city_61                   0.913  Female
5003         5172   city_21                   0.624    Male
5004         1815   city_27                   0.848    Male
...           ...       ...                     ...     ...
9995        27017   city_73                   0.754   Other
9996         7559  city_103                   0.920    Male
9997        12332  city_103                   0.920    Male
9998         3974  city_102                   0.804    Male
9999        13267   city_75                   0.939    Male

          relevent_experience enrolled_university education_level  \
5000  Has relevent experience       no_enrollment         Masters
5001  Has relevent experience       no_enrollment        Graduate
5002  Has relevent experience       no_enrollment        Graduate
5003   No relevent experience    Full time course        Graduate
5004  Has relevent experience       no_enrollment         Masters
...                       ...                 ...             ...
9995   No relevent experience       no_enrollment        Graduate
9996  Has relevent experience       no_enrollment        Graduate
9997   No relevent experience    Full time course        Graduate
9998  Has relevent experience    Full time course         Masters
9999  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size   company_type last_new_job  \
5000             STEM          9       10000+        Pvt Ltd            4
5001             STEM          7          <10        Pvt Ltd            1
5002             STEM        >20      100-500            NaN            1
5003             STEM          3          NaN            NaN        never
5004             STEM         18       10000+        Pvt Ltd           >4
...               ...        ...          ...            ...          ...
9995             STEM         <1          NaN            NaN        never
9996             STEM          4        50-99        Pvt Ltd            1
9997             STEM          2          NaN            NaN            1
9998             STEM          7       10000+  Public Sector            1
9999             STEM          9          NaN        Pvt Ltd            1

      training_hours  target
5000             170     0.0
5001             107     0.0
5002               9     0.0
5003              38     1.0
5004              17     1.0
...              ...     ...
9995               7     0.0
9996              42     0.0
9997              12     0.0
9998               2     1.0
9999              40     0.0

[5000 rows x 14 columns]
       enrollee_id      city  city_development_index  gender  \
10000        23427   city_24                   0.698     NaN
10001        17605   city_50                   0.896     NaN
10002        20912   city_73                   0.754     NaN
10003        13948  city_114                   0.926    Male
10004        15205  city_160                   0.920    Male
...            ...       ...                     ...     ...
14995         1305  city_103                   0.920    Male
14996        10310  city_103                   0.920  Female
14997        10689   city_21                   0.624     NaN
14998          605   city_16                   0.910    Male
14999        14587   city_16                   0.910    Male

           relevent_experience enrolled_university education_level  \
10000   No relevent experience                 NaN     High School
10001   No relevent experience       no_enrollment        Graduate
10002   No relevent experience    Full time course        Graduate
10003   No relevent experience       no_enrollment             Phd
10004   No relevent experience    Full time course     High School
...                        ...                 ...             ...
14995  Has relevent experience       no_enrollment        Graduate
14996  Has relevent experience       no_enrollment         Masters
14997  Has relevent experience    Full time course        Graduate
14998  Has relevent experience       no_enrollment        Graduate
14999  Has relevent experience       no_enrollment         Masters

      major_discipline experience company_size         company_type  \
10000              NaN          8          NaN                  NaN
10001             STEM        >20          NaN                  NaN
10002             STEM          5          NaN                  NaN
10003             STEM        >20       10000+              Pvt Ltd
10004              NaN          7      100-500              Pvt Ltd
...                ...        ...          ...                  ...
14995             Arts          9          <10                  NGO
14996             STEM         15    1000-4999              Pvt Ltd
14997            Other          5      100-500  Early Stage Startup
14998             STEM         11    5000-9999              Pvt Ltd
14999             STEM        >20        50-99              Pvt Ltd

      last_new_job  training_hours  target
10000        never              63     0.0
10001        never              10     0.0
10002        never              46     0.0
10003            1              18     0.0
10004            1              55     0.0
...            ...             ...     ...
14995            1              37     0.0
14996            3              39     0.0
14997            2              85     1.0
14998           >4               4     0.0
14999            1              14     0.0

[5000 rows x 14 columns]
       enrollee_id      city  city_development_index gender  \
15000         6178  city_103                   0.920    NaN
15001        27557   city_75                   0.939   Male
15002        27751  city_160                   0.920   Male
15003        11186  city_103                   0.920   Male
15004         1600  city_150                   0.698   Male
...            ...       ...                     ...    ...
19153         7386  city_173                   0.878   Male
19154        31398  city_103                   0.920   Male
19155        24576  city_103                   0.920   Male
19156         5756   city_65                   0.802   Male
19157        23834   city_67                   0.855    NaN

           relevent_experience enrolled_university education_level  \
15000  Has relevent experience       no_enrollment        Graduate
15001  Has relevent experience       no_enrollment        Graduate
15002  Has relevent experience       no_enrollment        Graduate
15003   No relevent experience       no_enrollment        Graduate
15004  Has relevent experience       no_enrollment        Graduate
...                        ...                 ...             ...
19153   No relevent experience       no_enrollment        Graduate
19154  Has relevent experience       no_enrollment        Graduate
19155  Has relevent experience       no_enrollment        Graduate
19156  Has relevent experience       no_enrollment     High School
19157   No relevent experience       no_enrollment  Primary School

      major_discipline experience company_size    company_type last_new_job  \
15000             Arts          2        50-99  Funded Startup            1
15001             STEM          6          NaN   Public Sector            1
15002             STEM          9        50-99         Pvt Ltd            1
15003             STEM         15          NaN             NaN           >4
15004             STEM         10          <10         Pvt Ltd            1
...                ...        ...          ...             ...          ...
19153       Humanities         14          NaN             NaN            1
19154             STEM         14          NaN             NaN            4
19155             STEM        >20        50-99         Pvt Ltd            4
19156              NaN         <1      500-999         Pvt Ltd            2
19157              NaN          2          NaN             NaN            1

       training_hours  target
15000              51     0.0
15001              12     1.0
15002               9     0.0
15003             156     0.0
15004              14     0.0
...               ...     ...
19153              42     1.0
19154              52     1.0
19155              44     0.0
19156              97     0.0
19157             127     0.0

[4158 rows x 14 columns]