In [1]:
import seaborn as sns 
import numpy as np
import pandas as pd

In [2]:
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
# Feature Scaling 

from sklearn.preprocessing import MinMaxScaler

In [4]:
minmax = MinMaxScaler().set_output(transform='pandas')
minmax

MinMaxScaler()

In [6]:
total_bill_scaled = minmax.fit_transform(tips[['total_bill']])
total_bill_scaled

     total_bill
0      0.291579
1      0.152283
2      0.375786
3      0.431713
4      0.450775
..          ...
239    0.543779
240    0.505027
241    0.410557
242    0.308965
243    0.329074

[244 rows x 1 columns]

In [10]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
from sklearn.preprocessing import StandardScaler

In [9]:
std_scl = StandardScaler().set_output(transform='pandas')
std_scl

StandardScaler()

In [12]:
tips_scalled = std_scl.fit_transform(tips[['tip']])
tips_scalled

          tip
0   -1.439947
1   -0.969205
2    0.363356
3    0.225754
4    0.443020
..        ...
239  2.115963
240 -0.722971
241 -0.722971
242 -0.904026
243  0.001247

[244 rows x 1 columns]

In [13]:
from sklearn.preprocessing import RobustScaler

In [14]:
R_scalar = RobustScaler().set_output(transform="pandas")
R_scalar

RobustScaler()

In [15]:
from sklearn.compose import ColumnTransformer

In [17]:
ct = ColumnTransformer(
    [('Robust_scalar', R_scalar , ['total_bill','tip'])]
).set_output(transform='pandas')

ct

ColumnTransformer(transformers=[('Robust_scalar', RobustScaler(),
                                 ['total_bill', 'tip'])])

In [18]:
ct.fit_transform(tips)

     Robust_scalar__total_bill  Robust_scalar__tip
0                    -0.074675             -1.2096
1                    -0.691558             -0.7936
2                     0.298237              0.3840
3                     0.545918              0.2624
4                     0.630334              0.4544
..                         ...                 ...
239                   1.042208              1.9328
240                   0.870594             -0.5760
241                   0.452226             -0.5760
242                   0.002319             -0.7360
243                   0.091373              0.0640

[244 rows x 2 columns]

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
ohe = OneHotEncoder(sparse_output=False, drop='first')
ohe

OneHotEncoder(drop='first', sparse_output=False)

In [35]:
ct2 = ColumnTransformer(
    [
        ('R_scale' ,R_scalar, ['total_bill' , 'tip']),
        ('Nominal' ,ohe, ['sex' ,'smoker' ,'day' ,'time'])
        
    ]
).set_output(transform='pandas')

ct2

ColumnTransformer(transformers=[('R_scale', RobustScaler(),
                                 ['total_bill', 'tip']),
                                ('Nominal',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['sex', 'smoker', 'day', 'time'])])

In [31]:
ct2 = ColumnTransformer(
    [
        ('Scale', R_scalar, ['total_bill', 'tip']),
        ('Nominal', ohe, ['sex', 'smoker', 'day', 'time'])
    ]
).set_output(transform='pandas')

ct2

ColumnTransformer(transformers=[('Scale', RobustScaler(),
                                 ['total_bill', 'tip']),
                                ('Nominal',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['sex', 'smoker', 'day', 'time'])])

In [36]:
ct2.fit_transform(tips)

,R_scale__total_bill,R_scale__tip,Nominal__sex_Male,Nominal__smoker_Yes,Nominal__day_Sat,Nominal__day_Sun,Nominal__day_Thur,Nominal__time_Lunch
0,-0.074675,-1.2096,0.0,0.0,0.0,1.0,0.0,0.0
1,-0.691558,-0.7936,1.0,0.0,0.0,1.0,0.0,0.0
2,0.298237,0.3840,1.0,0.0,0.0,1.0,0.0,0.0
3,0.545918,0.2624,1.0,0.0,0.0,1.0,0.0,0.0
4,0.630334,0.4544,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
239,1.042208,1.9328,1.0,0.0,1.0,0.0,0.0,0.0
240,0.870594,-0.5760,0.0,1.0,1.0,0.0,0.0,0.0
241,0.452226,-0.5760,1.0,1.0,1.0,0.0,0.0,0.0
242,0.002319,-0.7360,1.0,0.0,1.0,0.0,0.0,0.0
243,0.091373,0.0640,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
ct2 = ColumnTransformer(
    [
        ('Scale', R_scalar, ['total_bill', 'tip']),
        ('Nominal', ohe, ['sex', 'smoker', 'day', 'time'])
    ], remainder='passthrough'   # gives all the remaining columns in output
).set_output(transform='pandas')

ct2

ColumnTransformer(remainder='passthrough',
                  transformers=[('Scale', RobustScaler(),
                                 ['total_bill', 'tip']),
                                ('Nominal',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['sex', 'smoker', 'day', 'time'])])

In [41]:
ct2.fit_transform(tips)

,Scale__total_bill,Scale__tip,Nominal__sex_Male,Nominal__smoker_Yes,Nominal__day_Sat,Nominal__day_Sun,Nominal__day_Thur,Nominal__time_Lunch,remainder__size
0,-0.074675,-1.2096,0.0,0.0,0.0,1.0,0.0,0.0,2
1,-0.691558,-0.7936,1.0,0.0,0.0,1.0,0.0,0.0,3
2,0.298237,0.3840,1.0,0.0,0.0,1.0,0.0,0.0,3
3,0.545918,0.2624,1.0,0.0,0.0,1.0,0.0,0.0,2
4,0.630334,0.4544,0.0,0.0,0.0,1.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...
239,1.042208,1.9328,1.0,0.0,1.0,0.0,0.0,0.0,3
240,0.870594,-0.5760,0.0,1.0,1.0,0.0,0.0,0.0,2
241,0.452226,-0.5760,1.0,1.0,1.0,0.0,0.0,0.0,2
242,0.002319,-0.7360,1.0,0.0,1.0,0.0,0.0,0.0,2
243,0.091373,0.0640,0.0,0.0,0.0,0.0,1.0,0.0,2

In [44]:
ct2 = ColumnTransformer(
    [
        ('Scale', R_scalar, ['total_bill', 'tip']),
        ('Nominal', ohe, ['sex', 'smoker', 'day', 'time'])
    ], remainder='passthrough',   # gives all the remaining columns in output
    verbose_feature_names_out=False   # no prefixs are added to the column names

).set_output(transform='pandas')

ct2

ColumnTransformer(remainder='passthrough',
                  transformers=[('Scale', RobustScaler(),
                                 ['total_bill', 'tip']),
                                ('Nominal',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['sex', 'smoker', 'day', 'time'])],
                  verbose_feature_names_out=False)

In [45]:
ct2.fit_transform(tips)

,total_bill,tip,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch,size
0,-0.074675,-1.2096,0.0,0.0,0.0,1.0,0.0,0.0,2
1,-0.691558,-0.7936,1.0,0.0,0.0,1.0,0.0,0.0,3
2,0.298237,0.3840,1.0,0.0,0.0,1.0,0.0,0.0,3
3,0.545918,0.2624,1.0,0.0,0.0,1.0,0.0,0.0,2
4,0.630334,0.4544,0.0,0.0,0.0,1.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...
239,1.042208,1.9328,1.0,0.0,1.0,0.0,0.0,0.0,3
240,0.870594,-0.5760,0.0,1.0,1.0,0.0,0.0,0.0,2
241,0.452226,-0.5760,1.0,1.0,1.0,0.0,0.0,0.0,2
242,0.002319,-0.7360,1.0,0.0,1.0,0.0,0.0,0.0,2
243,0.091373,0.0640,0.0,0.0,0.0,0.0,1.0,0.0,2

In [46]:
def order_data(x):
    if x > 4:
        return 'L'
    elif x > 2:
        return 'M'
    else :
        return 'S'

In [47]:
tips['size'] = tips['size'].apply(order_data)
tips.head()

   total_bill   tip     sex smoker  day    time size
0       16.99  1.01  Female     No  Sun  Dinner    S
1       10.34  1.66    Male     No  Sun  Dinner    M
2       21.01  3.50    Male     No  Sun  Dinner    M
3       23.68  3.31    Male     No  Sun  Dinner    S
4       24.59  3.61  Female     No  Sun  Dinner    M

In [48]:
from sklearn.preprocessing import OrdinalEncoder

In [50]:
order = ['S','M','L']  # ascending order

oe = OrdinalEncoder(categories=[order])

oe

OrdinalEncoder(categories=[['S', 'M', 'L']])

In [51]:
ct3 = ColumnTransformer(
    [
        ('R_scalar',R_scalar,['total_bill','tip']),
        ('Nominal',ohe,['sex', 'smoker', 'day', 'time']),
        ('Ordinal',oe , ['size']),
    ],
    remainder='passthrough',
    verbose_feature_names_out=False
).set_output(transform='pandas')

ct3

ColumnTransformer(remainder='passthrough',
                  transformers=[('R_scalar', RobustScaler(),
                                 ['total_bill', 'tip']),
                                ('Nominal',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['sex', 'smoker', 'day', 'time']),
                                ('Ordinal',
                                 OrdinalEncoder(categories=[['S', 'M', 'L']]),
                                 ['size'])],
                  verbose_feature_names_out=False)

In [52]:
ct3.fit_transform(tips)

,total_bill,tip,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch,size
0,-0.074675,-1.2096,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,-0.691558,-0.7936,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.298237,0.3840,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.545918,0.2624,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.630334,0.4544,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
239,1.042208,1.9328,1.0,0.0,1.0,0.0,0.0,0.0,1.0
240,0.870594,-0.5760,0.0,1.0,1.0,0.0,0.0,0.0,0.0
241,0.452226,-0.5760,1.0,1.0,1.0,0.0,0.0,0.0,0.0
242,0.002319,-0.7360,1.0,0.0,1.0,0.0,0.0,0.0,0.0
243,0.091373,0.0640,0.0,0.0,0.0,0.0,1.0,0.0,0.0