## Categorical Encoding

In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [4]:
tips.sex.unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [6]:
ohe = OneHotEncoder()
ohe

OneHotEncoder()

In [7]:
tips.sex.to_frame()

        sex
0    Female
1      Male
2      Male
3      Male
4    Female
..      ...
239    Male
240  Female
241    Male
242    Male
243  Female

[244 rows x 1 columns]

In [8]:
ohe.fit_transform(tips.sex.to_frame())

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 244 stored elements and shape (244, 2)>

In [9]:
# sparse_output = True|False 

ohe1 = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
ohe1

OneHotEncoder(sparse_output=False)

In [10]:
ohe1.fit_transform(tips.sex.to_frame())

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [11]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [12]:
tips.day.nunique()

4

In [13]:
tips.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe = OneHotEncoder(sparse_output=False ).set_output(transform='pandas')
ohe

OneHotEncoder(sparse_output=False)

In [16]:
tips["day"]

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [17]:
ohe.fit_transform(tips.day.to_frame())

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [18]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [19]:
ohe.fit_transform(tips.smoker.to_frame())

     smoker_No  smoker_Yes
0          1.0         0.0
1          1.0         0.0
2          1.0         0.0
3          1.0         0.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[244 rows x 2 columns]

In [20]:
ohe.fit_transform(tips.time.to_frame())

     time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]

In [21]:
ohe.fit_transform(tips.day.to_frame())

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [22]:
## Regularization

ohe2 = OneHotEncoder(sparse_output=False , drop='first').set_output(transform='pandas')
ohe2

OneHotEncoder(drop='first', sparse_output=False)

In [23]:
ohe2.fit_transform(tips[['day']])

     day_Sat  day_Sun  day_Thur
0        0.0      1.0       0.0
1        0.0      1.0       0.0
2        0.0      1.0       0.0
3        0.0      1.0       0.0
4        0.0      1.0       0.0
..       ...      ...       ...
239      1.0      0.0       0.0
240      1.0      0.0       0.0
241      1.0      0.0       0.0
242      1.0      0.0       0.0
243      0.0      0.0       1.0

[244 rows x 3 columns]

In [24]:
ohe2.fit_transform(tips[['smoker']])

     smoker_Yes
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
..          ...
239         0.0
240         1.0
241         1.0
242         0.0
243         0.0

[244 rows x 1 columns]

In [25]:
ohe2.fit_transform(tips[['time']])

     time_Lunch
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
..          ...
239         0.0
240         0.0
241         0.0
242         0.0
243         0.0

[244 rows x 1 columns]

In [26]:
ohe2.fit_transform(tips[['sex']])

     sex_Male
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
239       1.0
240       0.0
241       1.0
242       1.0
243       0.0

[244 rows x 1 columns]

In [27]:
tips['size']

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [28]:
tips['size'].unique()
# if size < 2 == small group (s)
# is size 3,4 == medium group (m)
# if size 5,6 == large group (l)

array([2, 3, 4, 1, 6, 5])

In [29]:
def order_data(x):
    if x > 4:
        return 'L'
    elif x > 2:
        return 'M'
    else :
        return "S"

In [30]:
tips['size'].apply(order_data)

0      S
1      M
2      M
3      S
4      M
      ..
239    M
240    S
241    S
242    S
243    S
Name: size, Length: 244, dtype: object

In [31]:
tips['size'].apply(order_data).unique()

array(['S', 'M', 'L'], dtype=object)

In [33]:
tips["size_category"] = tips['size'].apply(order_data)
tips["size_category"]

0      S
1      M
2      M
3      S
4      M
      ..
239    M
240    S
241    S
242    S
243    S
Name: size_category, Length: 244, dtype: object

In [34]:
tips

     total_bill   tip     sex smoker   day    time  size size_category
0         16.99  1.01  Female     No   Sun  Dinner     2             S
1         10.34  1.66    Male     No   Sun  Dinner     3             M
2         21.01  3.50    Male     No   Sun  Dinner     3             M
3         23.68  3.31    Male     No   Sun  Dinner     2             S
4         24.59  3.61  Female     No   Sun  Dinner     4             M
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3             M
240       27.18  2.00  Female    Yes   Sat  Dinner     2             S
241       22.67  2.00    Male    Yes   Sat  Dinner     2             S
242       17.82  1.75    Male     No   Sat  Dinner     2             S
243       18.78  3.00  Female     No  Thur  Dinner     2             S

[244 rows x 8 columns]

In [35]:
from sklearn.preprocessing import OrdinalEncoder

In [38]:
oe = OrdinalEncoder().set_output(transform='pandas')
oe

OrdinalEncoder()

In [39]:
oe.fit_transform(tips[['size_category']])

     size_category
0              2.0
1              1.0
2              1.0
3              2.0
4              1.0
..             ...
239            1.0
240            2.0
241            2.0
242            2.0
243            2.0

[244 rows x 1 columns]

In [40]:
# to maintain a order 
order = [ 'S','M','L']

In [42]:
oe1 = OrdinalEncoder( categories=[order]).set_output(transform='pandas')
oe1

OrdinalEncoder(categories=[['S', 'M', 'L']])

In [43]:
oe1.fit_transform(tips[['size_category']])

     size_category
0              0.0
1              1.0
2              1.0
3              0.0
4              1.0
..             ...
239            1.0
240            0.0
241            0.0
242            0.0
243            0.0

[244 rows x 1 columns]

In [44]:
## Encoding 
ohe = OneHotEncoder(sparse_output=False , drop='first')
oe = OrdinalEncoder(categories=[order])

In [45]:
from sklearn.compose import ColumnTransformer

In [46]:
ct = ColumnTransformer([('OHE', ohe, ['sex','smoker', 'day' , 'time']),
                        ('OE', oe,['size_category'])],
                        remainder='passthrough').set_output(transform='pandas')

In [47]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('OHE',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['sex', 'smoker', 'day', 'time']),
                                ('OE',
                                 OrdinalEncoder(categories=[['S', 'M', 'L']]),
                                 ['size_category'])])

In [48]:
ct.fit_transform(tips)

,OHE__sex_Male,OHE__smoker_Yes,OHE__day_Sat,OHE__day_Sun,OHE__day_Thur,OHE__time_Lunch,OE__size_category,remainder__total_bill,remainder__tip,remainder__size
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,16.99,1.01,2
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,10.34,1.66,3
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,21.01,3.50,3
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,23.68,3.31,2
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,24.59,3.61,4
...,...,...,...,...,...,...,...,...,...,...
239,1.0,0.0,1.0,0.0,0.0,0.0,1.0,29.03,5.92,3
240,0.0,1.0,1.0,0.0,0.0,0.0,0.0,27.18,2.00,2
241,1.0,1.0,1.0,0.0,0.0,0.0,0.0,22.67,2.00,2
242,1.0,0.0,1.0,0.0,0.0,0.0,0.0,17.82,1.75,2
243,0.0,0.0,0.0,0.0,1.0,0.0,0.0,18.78,3.00,2

In [49]:
ct.fit_transform(tips[:])

,OHE__sex_Male,OHE__smoker_Yes,OHE__day_Sat,OHE__day_Sun,OHE__day_Thur,OHE__time_Lunch,OE__size_category,remainder__total_bill,remainder__tip,remainder__size
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,16.99,1.01,2
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,10.34,1.66,3
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,21.01,3.50,3
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,23.68,3.31,2
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,24.59,3.61,4
...,...,...,...,...,...,...,...,...,...,...
239,1.0,0.0,1.0,0.0,0.0,0.0,1.0,29.03,5.92,3
240,0.0,1.0,1.0,0.0,0.0,0.0,0.0,27.18,2.00,2
241,1.0,1.0,1.0,0.0,0.0,0.0,0.0,22.67,2.00,2
242,1.0,0.0,1.0,0.0,0.0,0.0,0.0,17.82,1.75,2
243,0.0,0.0,0.0,0.0,1.0,0.0,0.0,18.78,3.00,2