In [50]:
print("Hello World")

Hello World

In [51]:
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv('cars.csv')

df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [54]:
df.brand.value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [55]:
df.brand.nunique()

32

In [56]:
df.fuel.value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [57]:
df.owner.value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

### 1 One Hot Encoding Using Pandas

In [58]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [59]:
pd.get_dummies(df, columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

### K-1 OneHotEncoding

In [60]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### 3 . OneHotEncoding using sklearn

In [61]:
## train test split of data

from sklearn.model_selection import train_test_split

X_train , X_test, y_train , y_test = train_test_split(df.iloc[:,0:4] , df.iloc[:,-1] , test_size=0.2 , random_state=42)

In [62]:
X_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [63]:
X_test

          brand  km_driven    fuel         owner
1971      Honda     110000  Petrol   Third Owner
4664       Tata     291977  Diesel   First Owner
5448     Maruti      70000  Diesel   First Owner
3333      Honda     120000  Petrol  Second Owner
2316     Maruti      69000  Diesel  Second Owner
...         ...        ...     ...           ...
1149        BMW       8500  Diesel   First Owner
5002     Maruti      40000  Petrol   First Owner
6008    Hyundai      54043  Petrol   First Owner
2283       Tata      70000  Petrol   First Owner
5428  Chevrolet     110000  Petrol  Second Owner

[1626 rows x 4 columns]

In [64]:
y_train

6518    520000
6144    300000
6381    380000
438     530000
5939    335000
         ...
5226    475000
5390    530000
860     576000
7603    770000
7270    155000
Name: selling_price, Length: 6502, dtype: int64

In [65]:
y_test

1971     198000
4664     500000
5448     425000
3333     150000
2316     525000
         ...
1149    5500000
5002     370000
6008     374000
2283     575000
5428     140000
Name: selling_price, Length: 1626, dtype: int64

In [66]:
from sklearn.preprocessing import OneHotEncoder

In [67]:
ohe= OneHotEncoder()

In [68]:
X_train_new = ohe.fit_transform(X_train[['fuel' , 'owner']]).toarray()

X_test_new = ohe.fit_transform(X_test[['fuel' , 'owner']]).toarray()

In [69]:
X_train_new.shape

(6502, 9)

In [70]:
X_test_new.shape

(1626, 9)

In [71]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 11)

In [72]:
# if drop='first'  --> removes first column 

ohe = OneHotEncoder(drop='first')

In [73]:
X_train_new = ohe.fit_transform(X_train[['fuel' , 'owner']]).toarray()

X_test_new = ohe.fit_transform(X_test[['fuel' , 'owner']]).toarray()

In [74]:
X_test_new.shape

(1626, 7)

In [75]:
X_train_new.shape

(6502, 7)

In [76]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

In [77]:
# sparse = False

ohe = OneHotEncoder(drop='first' , sparse_output=False)

In [78]:
X_train_new = ohe.fit_transform(X_train[['fuel' , 'owner']])

X_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [79]:
X_train_new

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(6502, 7))

In [80]:
X_train_new.shape

(6502, 7)

In [81]:
X_test_new

array([[0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(1626, 7))

In [82]:
X_test_new.shape

(1626, 7)

In [83]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Tata', 2560, 0.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 80000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Hyundai', 150000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 1.0, 0.0, 0.0]],
      shape=(6502, 9), dtype=object)

In [84]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

In [85]:
# dtype


ohe = OneHotEncoder(drop='first' , sparse_output=False , dtype=np.int32)

In [86]:
X_train_new = ohe.fit_transform(X_train[['fuel' , 'owner']])

X_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [87]:
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], shape=(6502, 7), dtype=int32)

In [88]:
X_train_new.shape

(6502, 7)

In [89]:
X_test_new

array([[0, 0, 1, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], shape=(1626, 7), dtype=int32)

In [90]:
X_test_new.shape

(1626, 7)

In [91]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], shape=(6502, 9), dtype=object)

In [92]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

### 4 . OneHotEncoding with Top Categories

In [93]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [95]:
counts = df['brand'].value_counts()

In [96]:
df.brand.nunique()

32

In [97]:
threshold = 100

In [99]:
repl = counts[counts <= threshold].index

repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [100]:
pd.get_dummies(df['brand'].replace(repl , 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

In [101]:
pd.get_dummies(df['brand'].replace(repl , 'uncommon')).sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
497,False,False,False,False,True,False,False,False,False,False,False,False,False
806,False,False,False,False,False,False,False,False,False,True,False,False,False
7235,False,False,False,False,False,False,True,False,False,False,False,False,False
721,False,False,False,False,True,False,False,False,False,False,False,False,False
689,False,False,False,False,True,False,False,False,False,False,False,False,False
1227,False,False,False,False,False,True,False,False,False,False,False,False,False
3614,False,False,False,False,False,True,False,False,False,False,False,False,False
3655,False,False,False,False,False,False,True,False,False,False,False,False,False
7533,False,False,False,False,False,False,True,False,False,False,False,False,False
6775,False,False,False,False,False,False,False,False,False,False,False,True,False